name = "net-entreprise-scraper"
account_id = "27545095cf091397123f110c37709faf"
main = "build/worker/shim.mjs"
compatibility_date = "2026-07-17"
preview_urls = false

[cache]
enabled = true

[build]
command = "cargo install -q --locked worker-build@0.8.5 && worker-build --release"
