name = "net-entreprise-scraper"
main = "build/worker/shim.mjs"
compatibility_date = "2026-07-17"
preview_urls = false

[build]
command = "cargo install -q worker-build@0.8.5 && worker-build --release"
